# Generated by Django 4.1.13 on 2026-07-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_alter_historicaljob_crontab_alter_job_crontab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='scope',
            field=models.CharField(default='private', max_length=64, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='scope',
            field=models.CharField(default='private', max_length=64, verbose_name='Scope'),
        ),
    ]
