ARG VERSION=v4.10.16

FROM registry.fit2cloud.com/jumpserver/xpack:${VERSION} AS build-xpack
FROM registry.fit2cloud.com/jumpserver/core:${VERSION}-ce

COPY --from=build-xpack /opt/xpack /opt/jumpserver/apps/xpack

ARG TOOLS="                           \
        g++                           \
        curl                          \
        iputils-ping                  \
        netcat-openbsd                \
        nmap                          \
        telnet                        \
        vim                           \
        postgresql-client         \
        wget                          \
        poppler-utils"

ARG APT_MIRROR=https://mirrors.aliyun.com

RUN set -ex \
    && sed -i "s@http://.*.debian.org@${APT_MIRROR}@g" /etc/apt/sources.list.d/debian.sources \
    && apt-get update \
    && apt-get -y install --no-install-recommends ${TOOLS} \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/jumpserver

ARG PIP_MIRROR=https://mirrors.aliyun.com/pypi/simple/

RUN set -ex \
    && UV_HTTP_TIMEOUT=300 uv pip install -i${PIP_MIRROR} --group xpack \
    && playwright install chromium  --with-deps --only-shell
