# Generated by Django 4.1.13 on 2026-08-31 09:31

import common.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_user_wechat_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=common.db.fields.EncryptCharField(max_length=128, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=common.db.fields.EncryptCharField(max_length=128, verbose_name='Name'),
        ),
    ]
