# Generated by Django 4.1.13 on 2024-08-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_user_lark_id_alter_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_num',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Job Number'),
        ),
    ]
