# Generated by Django 4.1.13 on 2024-09-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_user_companies_user_job_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='org_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Organization Code'),
        ),
    ]
