# Generated by Django 4.1.13 on 2024-09-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_auto_20230110_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approver',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Approver'),
        ),
    ]
