# Generated by Django 4.1.13 on 2024-10-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_ticket_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
