# Generated by Django 4.1.13 on 2024-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_alter_setting_options'),
        ('settings', '0013_auto_20240326_1531'),
    ]

    operations = [
    ]
