# Generated by Django 4.1.13 on 2026-04-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_alter_asset_connectivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='value',
            field=models.CharField(max_length=256, verbose_name='Value'),
        ),
    ]
