# Generated by Django 4.1.13 on 2024-09-10 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0128_auto_20240514_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='director',
            field=models.ForeignKey(default=uuid.UUID('123e4567-e89b-12d3-a456-426614174000'), on_delete=django.db.models.deletion.PROTECT, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Director'),
        ),
    ]
