# Generated by Django 4.1.13 on 2024-07-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0128_auto_20240514_1521'),
        ('assets', '0128_favoritenode_favoriteasset_favoritenode'),
    ]

    operations = [
    ]
