# Generated by Django 4.1.13 on 2024-09-04 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0128_auto_20240514_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='director',
            field=models.ForeignKey(default=uuid.UUID('e2d854be-33c8-4374-affc-7a36a0d7e0bb'), on_delete=django.db.models.deletion.PROTECT, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Director'),
        ),
    ]
