# Generated by Django 4.1.13 on 2026-04-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DltAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(max_length=32, verbose_name='Name')),
                ('uid', models.CharField(max_length=32, verbose_name='UID')),
                ('org', models.CharField(max_length=32, verbose_name='Organization')),
                ('org_full_name', models.CharField(max_length=128, verbose_name='Organization Name')),
                ('email', models.CharField(max_length=32, verbose_name='Email')),
                ('mobile', models.CharField(max_length=32, verbose_name='Mobile')),
                ('status', models.CharField(default='0', max_length=2, verbose_name='Status')),
                ('action_type', models.CharField(max_length=10, verbose_name='Action Type')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': '登录通应用用户信息',
                'db_table': 'dlt_account',
            },
        ),
    ]
