# Generated by Django 4.1.13 on 2026-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dltaccount',
            name='email',
            field=models.CharField(max_length=128, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='dltaccount',
            name='org',
            field=models.CharField(max_length=128, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='dltaccount',
            name='uid',
            field=models.CharField(max_length=128, verbose_name='UID'),
        ),
    ]
