# Generated by Django 4.1.13 on 2024-09-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_organization_org_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_code',
        ),
    ]
